# Generated by Django 3.1.4 on 2022-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_converted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(default='', max_length=64),
        ),
    ]
