# Generated by Django 3.1.4 on 2022-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(default='', max_length=64),
        ),
    ]
