# Generated by Django 3.1.4 on 2022-05-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_leadssheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadssheet',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.agent'),
        ),
    ]
