# Generated by Django 3.1.4 on 2022-05-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_lead_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(related_name='leads', to='leads.Tag'),
        ),
    ]
