# Generated by Django 3.1.4 on 2022-05-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_auto_20220509_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_called',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
