# Generated by Django 3.1.4 on 2022-05-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_lead_last_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='click2call_extension',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.agent'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.Tag'),
        ),
    ]
