# Generated by Django 3.1.4 on 2022-05-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_auto_20220518_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[(None, '----------'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=32)),
                ('year', models.CharField(choices=[(None, '----------'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4)),
                ('performance', models.CharField(choices=[(None, '----------'), ('100', 'Excellent'), ('75', 'Good'), ('50', 'Needs improvement'), ('25', 'Bad')], max_length=3, verbose_name='What you think about this agent sales performance this month?')),
                ('kpi_rate', models.CharField(choices=[(None, '----------'), ('100', '80% - 100%'), ('75', '60% - 80%'), ('50', '40% - 60%'), ('25', '0%')], max_length=3, verbose_name='What KPI rate he deserves this month?')),
                ('revenu', models.CharField(choices=[(None, '----------'), ('100', '10,000$ - $50,000'), ('75', '5000$ - $10,000'), ('50', '1000$ - $5000'), ('25', '0$ - $1000')], max_length=3, verbose_name='How much revenue the sales agent made this month?')),
                ('best_service', models.CharField(choices=[(None, '----------'), ('100', 'Copy Trading'), ('75', 'Course'), ('50', 'Signals'), ('25', 'Consultation')], max_length=3, verbose_name="Which service you think he's best at this month?")),
                ('customer_support', models.CharField(choices=[(None, '----------'), ('100', '80% - 100%'), ('75', '60% - 80%'), ('50', '40% - 60%'), ('25', '0%')], max_length=3, verbose_name='Customer Support Performance?')),
                ('total_rate', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='leads.agent')),
            ],
        ),
    ]
