# Generated by Django 4.0.5 on 2022-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_salesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='month',
            field=models.CharField(choices=[(None, '----------'), ('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_rate',
            field=models.CharField(max_length=3),
        ),
        migrations.AddField(
            model_name='agent',
            name='permissions',
            field=models.ManyToManyField(related_name='agent_permissions', to='leads.permission'),
        ),
    ]
