# Generated by Django 4.0.5 on 2022-06-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('leads', '0023_permission_alter_salesreport_month_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AlterField(
            model_name='agent',
            name='permissions',
            field=models.ManyToManyField(related_name='agent_permissions', to='permissions.permission'),
        ),
    ]
