# Generated by Django 3.1.4 on 2022-06-22 10:31

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_agent_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadssheet',
            name='random',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='category',
            name='organisation',
        ),
        migrations.AddField(
            model_name='category',
            name='organisation',
            field=models.ManyToManyField(to='leads.UserProfile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(default=leads.models.get_default_category, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.category'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
