# Generated by Django 4.0.5 on 2022-06-15 13:02

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_agent_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(default=leads.models.get_default_category, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.category'),
        ),
    ]
