# Generated by Django 4.0.5 on 2022-06-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_remove_category_organisation_category_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadssheet',
            name='random',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='leadssheet',
            name='agent',
        ),
        migrations.AddField(
            model_name='leadssheet',
            name='agent',
            field=models.ManyToManyField(blank=True, null=True, to='leads.agent'),
        ),
    ]
