# Generated by Django 4.0.5 on 2022-06-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_leadssheet_random_remove_leadssheet_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadssheet',
            name='agent',
        ),
        migrations.AddField(
            model_name='leadssheet',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.agent'),
        ),
    ]
