from .sales_report import *
from .agent_stats import *
from .dashboard_stats import *
from .tags import *
from .sheets import *
from .click2call import *
from .upload import *
from .catgs import *
from .ajax import *
from .followups import *
from .search import *
from .leads_views import *
