# Generated by Django 4.0.5 on 2022-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_permission_code_alter_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.SlugField(default='', max_length=30, unique=True),
        ),
    ]
