# Generated by Django 4.0.5 on 2022-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_permission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
