# Generated by Django 3.1.4 on 2022-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_alter_permission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
